$font = UbuntuMono Nerd Font

general {
    hide_cursor = true
    ignore_empty_input = true
    fail_timeout = 3000
}

animations {
    enabled = true
    bezier = smooth, 0.16, 1, 0.3, 1
    animation = fadeIn, 1, 4, smooth
    animation = fadeOut, 1, 4, smooth
    animation = inputFieldDots, 1, 2, smooth
    animation = inputFieldColors, 1, 6, smooth
}

background {
    monitor =
    path = ~/Pictures/gokulight.jpg
}

input-field {
    monitor =
    size = 380, 55
    outline_thickness = 2
    inner_color = rgba(00000099)
    outer_color = rgba(ffffffff99)
    check_color = rgba(ffffffffcc)
    fail_color = rgba(e67878ff)
    capslock_color = rgba(e6c878ff)
    font_color = rgba(ffffffff)
    font_family = $font
    rounding = 10
    placeholder_text = <i>Password...</i>
    fail_text = $PAMFAIL
    check_text = Authenticating...
    dots_spacing = 0.25
    dots_size = 0.3
    fade_on_empty = false
    position = 0, -20
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 5
}

label {
    monitor =
    text = $TIME
    font_size = 110
    font_family = $font
    color = rgba(ffffffff)
    position = 0, 150
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 6
    shadow_color = rgba(000000cc)
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 26
    font_family = $font
    color = rgba(ffffffff)
    position = 0, 90
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(000000cc)
}
