local cfg = vim.fn.stdpath("config")

-- vim.cmd.source() for Vimscript files (.vim)
-- dofile()         for Lua files (.lua)

vim.cmd.source(cfg .. "/general/settings.vim")
dofile(cfg .. "/vim-plug/plugins.lua")
vim.cmd.source(cfg .. "/keys/which-key.vim")
vim.cmd.source(cfg .. "/keys/mappings.vim")
vim.cmd.source(cfg .. "/themes/tokyonight.vim")
vim.cmd.source(cfg .. "/themes/lualine.vim")
dofile(cfg .. "/plug-config/nvim-tree.lua")
dofile(cfg .. "/plug-config/comment.lua")
dofile(cfg .. "/plug-config/lsp.lua")
vim.cmd.source(cfg .. "/plug-config/telescope.vim")
dofile(cfg .. "/plug-config/flash.lua")
vim.cmd.source(cfg .. "/plug-config/quickscope.vim")
dofile(cfg .. "/plug-config/toggleterm.lua")
vim.cmd.source(cfg .. "/plug-config/gitsigns.vim")
vim.cmd.source(cfg .. "/plug-config/dashboard.vim")
vim.cmd.source(cfg .. "/plug-config/mundo.vim")
vim.cmd.source(cfg .. "/plug-config/indent-blankline.vim")
vim.cmd.source(cfg .. "/plug-config/auto-save.vim")
vim.cmd.source(cfg .. "/plug-config/markview.vim")
dofile(cfg .. "/plug-config/lint.lua")
